## Простейшие операции на языке Julia

In [1]:
2 + 3

5

In [2]:
print("Hello, world!")

Hello, world!

In [3]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


## Основы синтаксиса Julia на примерах

In [4]:
typeof(3), typeof(3.5), typeof(3/3.55), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [5]:
1.0/0.0, 1.0/(-0.0), (0.0/0.0)

(Inf, -Inf, NaN)

In [6]:
typeof(1.0/0.0), typeof(1.0/(-0.0)), typeof((0.0/0.0))

(Float64, Float64, Float64)

In [7]:
for T in [Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128]
    println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [8]:
# преобразование прямым указанием
Int64(2.0), Char(2), typeof(Char(2))

(2, '\x02', Char)

In [9]:
# преобразование обобщенным оператором
convert(Int64, 2.0), convert(Char, 2)

(2, '\x02')

In [10]:
# преобразование нескольких аргументов к одному типу
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [11]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [12]:
f(4)

16

In [13]:
g(x) = x^2

g (generic function with 1 method)

In [14]:
g(8)

64

In [15]:
a = [4 7 6] # вектор-строка
b = [1, 2, 3] # вектор-столбец
a[2], b[2] #получим вторые элементы векторов a и b

(7, 2)

In [16]:
a = 1; b = 2; c = 3; d = 4 # присвоение значенний
Am = [a b; c d] # матрица размером 2x2

2×2 Matrix{Int64}:
 1  2
 3  4

In [17]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2] # элементы матрицы Am

(1, 2, 3, 4)

In [18]:
aa = [1 2] # вектор-строка
AA = [1 2; 3 4] # матрица 2x2
aa*AA*aa' # умножение вектор-строка на матрицу и на вектор-столбец (операция трансонирования)

1×1 Matrix{Int64}:
 27

In [19]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

##  Задания для самостоятельной работы

1. Изучите документацию по основным функциям Julia для чтения / записи / вывода информации на экран: read(), readline(), readlines(), readdlm(), print(),println(), show(), write(). Приведите свои примеры их использования, поясняя особенности их применения.

In [20]:
?read()

```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [21]:
?readline()

```
readline(io::IO=stdin; keep::Bool=false)
readline(filename::AbstractString; keep::Bool=false)
```

Read a single line of text from the given I/O stream or file (defaults to `stdin`). When reading from a file, the text is assumed to be encoded in UTF-8. Lines in the input end with `'\n'` or `"\r\n"` or the end of an input stream. When `keep` is false (as it is by default), these trailing newline characters are removed from the line before it is returned. When `keep` is true, they are returned as part of the line.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readline("my_file.txt")
"JuliaLang is a GitHub organization."

julia> readline("my_file.txt", keep=true)
"JuliaLang is a GitHub organization.\n"

julia> rm("my_file.txt")
```

```julia-repl
julia> print("Enter your name: ")
Enter your name:

julia> your_name = readline()
Logan
"Logan"
```


In [22]:
?readlines()

```
readlines(io::IO=stdin; keep::Bool=false)
readlines(filename::AbstractString; keep::Bool=false)
```

Read all lines of an I/O stream or a file as a vector of strings. Behavior is equivalent to saving the result of reading [`readline`](@ref) repeatedly with the same arguments and saving the resulting lines as a vector of strings.  See also [`eachline`](@ref) to iterate over the lines without reading them all at once.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readlines("my_file.txt")
2-element Vector{String}:
 "JuliaLang is a GitHub organization."
 "It has many members."

julia> readlines("my_file.txt", keep=true)
2-element Vector{String}:
 "JuliaLang is a GitHub organization.\n"
 "It has many members.\n"

julia> rm("my_file.txt")
```


In [23]:
?print()

```
print([io::IO], xs...)
```

Write to `io` (or to the default output stream [`stdout`](@ref) if `io` is not given) a canonical (un-decorated) text representation. The representation used by `print` includes minimal formatting and tries to avoid Julia-specific details.

`print` falls back to calling `show`, so most types should just define `show`. Define `print` if your type has a separate "plain" representation. For example, `show` displays strings with quotes, and `print` displays strings without quotes.

See also [`println`](@ref), [`string`](@ref), [`printstyled`](@ref).

# Examples

```jldoctest
julia> print("Hello World!")
Hello World!
julia> io = IOBuffer();

julia> print(io, "Hello", ' ', :World!)

julia> String(take!(io))
"Hello World!"
```


In [24]:
?println()

```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [25]:
?show()

```
show([io::IO = stdout], x)
```

Write a text representation of a value `x` to the output stream `io`. New types `T` should overload `show(io::IO, x::T)`. The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

[`repr`](@ref) returns the output of `show` as a string.

For a more verbose human-readable text output for objects of type `T`, define `show(io::IO, ::MIME"text/plain", ::T)` in addition. Checking the `:compact` [`IOContext`](@ref) key (often checked as `get(io, :compact, false)::Bool`) of `io` in such methods is recommended, since some containers show their elements by calling this method with `:compact => true`.

See also [`print`](@ref), which writes un-decorated representations.

# Examples

```jldoctest
julia> show("Hello World!")
"Hello World!"
julia> print("Hello World!")
Hello World!
```

---

```
show(io::IO, mime, x)
```

The [`display`](@ref) functions ultimately call `show` in order to write an object `x` as a given `mime` type to a given I/O stream `io` (usually a memory buffer), if possible. In order to provide a rich multimedia representation of a user-defined type `T`, it is only necessary to define a new `show` method for `T`, via: `show(io, ::MIME"mime", x::T) = ...`, where `mime` is a MIME-type string and the function body calls [`write`](@ref) (or similar) to write that representation of `x` to `io`. (Note that the `MIME""` notation only supports literal strings; to construct `MIME` types in a more flexible manner use `MIME{Symbol("")}`.)

For example, if you define a `MyImage` type and know how to write it to a PNG file, you could define a function `show(io, ::MIME"image/png", x::MyImage) = ...` to allow your images to be displayed on any PNG-capable `AbstractDisplay` (such as IJulia). As usual, be sure to `import Base.show` in order to add new methods to the built-in Julia function `show`.

Technically, the `MIME"mime"` macro defines a singleton type for the given `mime` string, which allows us to exploit Julia's dispatch mechanisms in determining how to display objects of any given type.

The default MIME type is `MIME"text/plain"`. There is a fallback definition for `text/plain` output that calls `show` with 2 arguments, so it is not always necessary to add a method for that case. If a type benefits from custom human-readable output though, `show(::IO, ::MIME"text/plain", ::T)` should be defined. For example, the `Day` type uses `1 day` as the output for the `text/plain` MIME type, and `Day(1)` as the output of 2-argument `show`.

# Examples

```jldoctest
julia> struct Day
           n::Int
       end

julia> Base.show(io::IO, ::MIME"text/plain", d::Day) = print(io, d.n, " day")

julia> Day(1)
1 day
```

Container types generally implement 3-argument `show` by calling `show(io, MIME"text/plain"(), x)` for elements `x`, with `:compact => true` set in an [`IOContext`](@ref) passed as the first argument.


In [26]:
?write()

```
write(io::IO, x)
write(filename::AbstractString, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call. i.e. the following are equivalent:

```
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```


### Пример:

In [27]:
message = IOBuffer("Hello, world!");
read(message, String)

"Hello, world!"

In [28]:
open("myfile.txt", "w") do io
    write(io, "Hello this is lab1!\n");
end

20

In [29]:
readline("myfile.txt")

"Hello this is lab1!"

In [30]:
readline("myfile.txt", keep = true)

"Hello this is lab1!\n"

In [2]:
write("my_file.txt", "Using function write()ia!.\n Lorem Ipsum is simply dummy
    text of the printing and typesetting industry.\n Lorem Ipsum has been 
    the industry's standard dummy text ever since the 1500s.")

190

In [31]:
readlines("my_file.txt")

3-element Vector{String}:
 "Using function write()ia!"
 "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

In [32]:
readlines("my_file.txt", keep = true)

3-element Vector{String}:
 "Using function write()ia!\n"
 "Lorem Ipsum is simply dummy text of the printing and typesetting industry.\n"
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

In [33]:
using DelimitedFiles
x = [1; 2; 3; 4];
y = [5; 6; 7; 8];
open("delimited_file.txt", "w") do io
    writedlm(io, [x y])
end;
readdlm("delimited_file.txt", Int32)

4×2 Matrix{Int32}:
 1  5
 2  6
 3  7
 4  8

In [34]:
print("Hello,")
print("World!")

Hello,World!

In [35]:
println("Hello,")
println("World!")

Hello,
World!


In [36]:
show("This is lab1")

"This is lab1"

In [37]:
data_to_write = "Using function write()"
write("myfile.txt", data_to_write)

22

2. Изучите документацию по функции parse(). Приведите свои примеры её использования, поясняя особенности её применения.

In [38]:
?parse()

```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.


In [39]:
str_num = "18"
parse_int = parse(Int, str_num)
println("Parsed integer: ", parse_int)

Parsed integer: 18


In [40]:
parse(Complex{Float64}, "1.2e-1 + 3.4im")

0.12 + 3.4im

3. Изучите синтаксис Julia для базовых математических операций с разным типом переменных: сложение, вычитание, умножение, деление, возведение в степень, извлечение корня, сравнение, логические операции. Приведите свои примеры с пояснениями по особенностям их применения.

In [41]:
a = 3
b = 4
println("Сложение: ", a + b)
println("Вычитание: ", a - b)
println("Умножение: ", a * b)
println("Деление: ", a / b)
println("Возведение в степень: ", a ^ b)
println("Извлечение корня: ", sqrt(a))

Сложение: 7
Вычитание: -1
Умножение: 12
Деление: 0.75
Возведение в степень: 81
Извлечение корня: 1.7320508075688772


In [42]:
#  Сравнение
x = 5
y = 6
println("Is x equal to y? ", x == y)
println("Is x not equal to y? ", x != y)
println("Is x smaller than y? ", x < y)
println("Is x greater than y? ", x > y)

Is x equal to y? false
Is x not equal to y? true
Is x smaller than y? true
Is x greater than y? false


In [43]:
# Логические операции
false && false

false

In [44]:
false && true

false

In [45]:
true || false

true

In [46]:
println("Logical AND: ", x < 10 && y < 10)
println("Logical OR: ", x < 10 || x > 10)

Logical AND: true
Logical OR: true


4. Приведите несколько своих примеров с пояснениями с операциями над матрицами и векторами: сложение, вычитание, скалярное произведение, транспонирование, умножение на скаляр.

In [47]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [48]:
B = [1 2 2; 2 3 3; 5 4 4]

3×3 Matrix{Int64}:
 1  2  2
 2  3  3
 5  4  4

In [49]:
# сложение
A + B

3×3 Matrix{Int64}:
  2   4   5
  6   8   9
 12  12  13

In [50]:
#  вычитание
A - B

3×3 Matrix{Int64}:
 0  0  1
 2  2  3
 2  4  5

In [51]:
# скалярное произведение векторов
v1 = [1, 2, 3]
v2 = [4, 5, 6]
print("Скалярное произведение векторов: ", sum(v1 .* v2))

Скалярное произведение векторов: 32

In [52]:
# транспонирование матрица A
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7
 2  5  8
 3  6  9

In [53]:
# умножение на скаляр
s = 3
print("Матрица A, умножение на скаляр: ", A * s)

Матрица A, умножение на скаляр: [3 6 9; 12 15 18; 21 24 27]