In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
    println(n)
end

1
3
5
7
9


In [4]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [5]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))

# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [6]:
# инициализация массива m x n из нулей:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [7]:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [8]:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
N = 15
if (N % 3 == 0) && (N % 5 == 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

FizzBuzz


In [9]:
x = 5
y = 10
(x > y) ? x : y

10

## Функции

In [10]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end

# функция возведения в квадрат:
function f(x)
    x^2
end

f (generic function with 1 method)

In [11]:
sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [12]:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2

sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [13]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x^2
sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [14]:
# задаём массив v:
v = [3, 5, 2]
sort(v)
v

3-element Vector{Int64}:
 3
 5
 2

In [15]:
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

In [16]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [17]:
x -> x^3
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

In [18]:
f(x) = x^2
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [19]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [20]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [21]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [22]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [23]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

## Сторонние библиотеки (пакеты) в Julia

In [24]:
import Pkg
Pkg.add("Example")

   Resolving package versions...
  No Changes to `C:\Users\Reachna\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\Reachna\.julia\environments\v1.9\Manifest.toml`


In [25]:
Pkg.add("Colors")
using Colors

   Resolving package versions...
  No Changes to `C:\Users\Reachna\.julia\environments\v1.9\Project.toml`
  No Changes to `C:\Users\Reachna\.julia\environments\v1.9\Manifest.toml`


In [26]:
palette = distinguishable_colors(100)

In [27]:
rand(palette, 3, 3)

## Задания для самостоятельного выполнения

In [28]:
# task1
for i in 1:1:100
    println(i)
end

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [29]:
i = 1
while i <= 100
    println(i^2)
    i += 1
end

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000


In [30]:
squares = Dict{Int64, Int64}()
for i in 1:1:100
    push!(squares, i => i^2)
end
pairs(squares)

Dict{Int64, Int64} with 100 entries:
  5  => 25
  56 => 3136
  35 => 1225
  55 => 3025
  60 => 3600
  30 => 900
  32 => 1024
  6  => 36
  67 => 4489
  45 => 2025
  73 => 5329
  64 => 4096
  90 => 8100
  4  => 16
  13 => 169
  54 => 2916
  63 => 3969
  86 => 7396
  91 => 8281
  62 => 3844
  58 => 3364
  52 => 2704
  12 => 144
  28 => 784
  75 => 5625
  ⋮  => ⋮

In [31]:
num = []
for i in 1:1:100
    append!(num, i)
end

squares_arr = []
i = 1
while i<= length(num)
    append!(squares_arr, num[i]^2)
    i += 1
end
squares_arr

100-element Vector{Any}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [32]:
# Task2
n = 7
if n % 2 == 0
    println("Четное число")
else
    println("Нечетное число")
end

Нечетное число


In [33]:
n = 4
n % 2 == 0 ? println("Четное число") : println("Нечетное число")

Четное число


In [34]:
# Task3
function add_one(n)
    n + 1
end
add_one(3)

4

In [35]:
# Task4
A = fill(1, 3 * 3)
B = collect(0: (length(A) - 1))
A = reshape(map(+, A, B), (3, 3))

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [36]:
# Task5
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [37]:
A ^ 3

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [38]:
for i in 7:1:9
    A[i] += A[i-3]
end
A

3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

In [39]:
# Task6
B = Array{Int32, 2}(undef, 15, 3)

for i in 1:1:15
    B[i, 1] = 10
    B[i, 2] = -10
    B[i, 3] = 10
end
B

15×3 Matrix{Int32}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [40]:
C = (B') * B
C

3×3 Matrix{Int32}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

In [41]:
# Task7
Z = zeros(Int64, 6, 6)

6×6 Matrix{Int64}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [42]:
E = ones(Int64, 6, 6)

6×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

In [43]:
Z1 = zeros(Int64, 6, 6)
for i in 1:6
    if i != 1
        Z1[i, i - 1] = E[i, i - 1]
    end
    if i != 6
        Z1[i, i + 1] = E[i, i + 1]
    end
end
Z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [44]:
Z2 = zeros(Int64, 6, 6)
for i in 1:6
    Z2[i, i] = 1
    
    if i + 2 <= 6
        Z2[i, i + 2] = E[i, i + 2]
    end
    
    if i - 2 >= 1
        Z2[i, i - 2] = E[i, i - 2]
    end
end
Z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 1  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [45]:
Z3  = zeros(Int64, 6, 6)
for i in 1:6
    Z3[i, 7-i] = 1
    
    if 7 - i + 2 <= 6
        Z3[i, 9-i] = E[i, 9-i]
    end
    
    if 7 - i - 2 >= 1
        Z3[i, 5-i] = E[i, 5-i]
    end
end
Z3

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  0
 1  0  1  0  0  0

In [46]:
Z4 = zeros(Int64, 6, 6)
for i in 1:6
    Z4[i, i] = 1
    if i+2 <= 6
        Z4[i, i+2] = E[i, i+2]
    end
    if i-2 >= 1
        Z4[i, i-2] = E[i, i-2]
    end
    if i+4 <= 6
        Z4[i, i+4] = E[i, i+4]
    end
    if i-4 >= 1
        Z4[i, i-4] = E[i, i-4]
    end
end
Z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

In [47]:
# Task8
function outer(x, y, operation)
    if (ndims(x) == 1) x = reshape(x, (size(x, 1), size(x, 2))) end
    if (ndims(y) == 1) y = reshape(y, (size(y, 1), size(y, 2))) end
    c = zeros(size(x)[1], size(y)[2])
    for i in 1:size(x)[1], j in 1:size(y)[2], k in 1:size(x)[2]
        c[i, j] += operation(x[i, k], y[k, j])
    end
    return c
end

outer (generic function with 1 method)

In [48]:
# Checking the correctness
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [49]:
A * A

3×3 Matrix{Int64}:
  0   0   0
  3   3   9
 -1  -1  -3

In [50]:
outer(A, A, *)

3×3 Matrix{Float64}:
  0.0   0.0   0.0
  3.0   3.0   9.0
 -1.0  -1.0  -3.0

In [51]:
A1 = outer(collect(0:4), collect(0:4)', +)

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  5.0
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0

In [52]:
A2 = outer(collect(0:4), collect(1:5)', ^)

5×5 Matrix{Float64}:
 0.0   0.0   0.0    0.0     0.0
 1.0   1.0   1.0    1.0     1.0
 2.0   4.0   8.0   16.0    32.0
 3.0   9.0  27.0   81.0   243.0
 4.0  16.0  64.0  256.0  1024.0

In [53]:
A3 = outer(collect(0:4), collect(0:4)', +) .% 5

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  0.0
 2.0  3.0  4.0  0.0  1.0
 3.0  4.0  0.0  1.0  2.0
 4.0  0.0  1.0  2.0  3.0

In [54]:
A4  = outer(collect(0:9), collect(0:9)', +) .% 10

10×10 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0
 2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0
 3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0
 4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0
 5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0
 6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0
 7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0
 8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0
 9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [55]:
A5 = outer(collect(0:8), collect(-9:-1)', -) .% 9

9×9 Matrix{Float64}:
 0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0
 1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0
 2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0
 3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0
 4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0
 5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0
 6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0
 7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0
 8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0

In [56]:
# Task9
# зададим коэффициенты из системы уравнений
array_sys = Array{Int64, 2}(undef, 5, 5)
m = 5
n = 5

for i in 1:1:m
    for j in 1:1:n
        array_sys[i, j] = 1 + abs(i - j)
    end
end
println(round.(Int32, array_sys))


# обозначим ответы
results = [7; -1; -3; 5; 17]

Int32[1 2 3 4 5; 2 1 2 3 4; 3 2 1 2 3; 4 3 2 1 2; 5 4 3 2 1]


5-element Vector{Int64}:
  7
 -1
 -3
  5
 17

In [57]:
# с помощью обратной матрицы получим решение данной матрицы
array_sys_inv = inv(array_sys)
round.(Int, array_sys_inv)
x_n = round.(Int, array_sys_inv * results)

5-element Vector{Int64}:
 -2
  3
  5
  2
 -4

In [58]:
# Task 10
M = rand(1:10, 6, 10)

6×10 Matrix{Int64}:
 9   7   1  3   5  1  9  8  4  1
 4   8   3  8   7  9  6  4  9  7
 7   8   4  3  10  9  5  1  5  4
 9   6  10  1   7  5  8  5  2  6
 4   2   5  5   7  4  4  9  8  8
 1  10   2  4   7  4  7  7  6  6

In [59]:
N = 4
for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] > N
            count += 1
        end
    end
    println("Количество элементов больше ", N, " в строке = ", i, " равно ", count)
end

Количество элементов больше 4 в строке = 1 равно 5
Количество элементов больше 4 в строке = 2 равно 7
Количество элементов больше 4 в строке = 3 равно 6
Количество элементов больше 4 в строке = 4 равно 8
Количество элементов больше 4 в строке = 5 равно 6
Количество элементов больше 4 в строке = 6 равно 6


In [60]:
M_ = 7
for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] == M_
            count += 1
        end
    end
    if count == 2
        println("Число ", M_, " встречается в строке ", i, " равно 2 раза")
    end
end

Число 7 встречается в строке 2 равно 2 раза


In [61]:
function sum_75(matrix, K)
    matrix_new = rand(10)
    for i in 1:1:10
        sum = 0 
        for j in 1:1:6
            sum += matrix[j, i]
        end
        matrix_new[i] = sum
    end
    # теперь просуммируем все значения matrix_new попарно
    for i in 1:1:10
        for j in i+1:1:10
            sum = matrix_new[i] + matrix_new[j]
            if sum > K
                println("Столбцы - ", i, " и ", j)
            end
        end
    end
end

sum_75 (generic function with 1 method)

In [62]:
sum_75(M, 75)

Столбцы - 1 и 5
Столбцы - 2 и 5
Столбцы - 2 и 7
Столбцы - 5 и 7
Столбцы - 5 и 8
Столбцы - 5 и 9


In [63]:
# Task11
s1 = 0
for i in 1:20
    for j in 1:5
        s1 += (i^4)/(3+j)
    end
end
println(s1)

639215.2833333334


In [64]:
s2 = 0
for i in 1:20
    for j in 1:5
        s2 += (i^4)/(3+i*j)
    end
end
print(s2)

89912.02146097136