##  Кортежи

In [1]:
# пустой кортеж:
()

()

In [2]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [4]:
# кортеж из элементов разных типов:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [5]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [6]:
# Примеры операций над кортежами:
# длина кортежа x2:
length(x2)

3

In [7]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [8]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [9]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [10]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

## Словари

In [11]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [12]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [13]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [14]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [15]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [16]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [17]:
# удалить ключ и связанные с ним значения из словаря
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [18]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

 ## Множества

In [19]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [20]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [21]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [22]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [23]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [24]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [25]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [26]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [27]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [28]:
# удаление последнего элемента множества:
pop!(S4)

2

## Массивы

In [29]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [30]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]

Int64[]

In [31]:
empty_array_3 = (Float64)[]

Float64[]

In [32]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [33]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [34]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [35]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.321668  0.486016  0.0357191  0.475654  …  0.681394  0.495768  0.515487

In [36]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0601193  0.600416  0.90214
 0.870783   0.651348  0.691781
 0.373909   0.324747  0.371572
 0.216877   0.223216  0.452818

[:, :, 2] =
 0.663434  0.291783  0.562177
 0.273255  0.394848  0.145918
 0.191051  0.241634  0.66974
 0.541105  0.901492  0.52052

In [37]:
# Примеры массивов, заданных некоторыми функциями через включение:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [38]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [39]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [40]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [41]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [42]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [43]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [44]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [45]:
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [46]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)

12-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [47]:
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [48]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [49]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [50]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 20  10  18  16  11
 17  17  17  10  19
 11  15  17  19  15
 14  11  19  18  18
 18  10  17  16  20
 19  13  12  18  18
 13  16  14  19  16
 16  16  13  18  16
 14  17  14  13  14
 15  16  14  13  16

In [51]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 10
 17
 15
 11
 10
 13
 16
 16
 17
 16

In [52]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 10  11
 17  19
 15  15
 11  18
 10  20
 13  18
 16  16
 16  16
 17  14
 16  16

In [53]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 10  18  16
 17  17  10
 15  17  19
 11  19  18
 10  17  16
 13  12  18
 16  14  19
 16  13  18
 17  14  13
 16  14  13

In [54]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 17  19
 14  18
 19  18

In [55]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 18
 16
 11

In [56]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 11  10  12  10  11
 13  10  13  13  14
 14  11  14  13  15
 14  13  14  16  16
 15  15  14  16  16
 16  16  17  18  16
 17  16  17  18  18
 18  16  17  18  18
 19  17  18  19  19
 20  17  19  19  20

In [57]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  11  16  18  20
 10  17  17  17  19
 11  15  15  17  19
 11  14  18  18  19
 10  16  17  18  20
 12  13  18  18  19
 13  14  16  16  19
 13  16  16  16  18
 13  14  14  14  17
 13  14  15  16  16

In [58]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 1  0  1  1  0
 1  1  1  0  1
 0  1  1  1  1
 0  0  1  1  1
 1  0  1  1  1
 1  0  0  1  1
 0  1  0  1  1
 1  1  0  1  1
 0  1  0  0  0
 1  1  0  0  1

In [59]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

32-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(5, 1)
 CartesianIndex(6, 1)
 CartesianIndex(8, 1)
 CartesianIndex(10, 1)
 CartesianIndex(2, 2)
 CartesianIndex(3, 2)
 CartesianIndex(7, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(10, 2)
 CartesianIndex(1, 3)
 ⋮
 CartesianIndex(5, 4)
 CartesianIndex(6, 4)
 CartesianIndex(7, 4)
 CartesianIndex(8, 4)
 CartesianIndex(2, 5)
 CartesianIndex(3, 5)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(7, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

##  Задания для самостоятельного выполнения

In [60]:
# Задания 1
# Определение множеств
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

# Вычисление пересечений и объединений
P = union(intersect(A, B), intersect(A, B), intersect(A, C), intersect(B, C))

# вывод
println("P: ",P)

P: Set([0, 4, 7, 9, 3, 1])


In [61]:
# Задания 2
# Создание множество 
set1 = Set([1, "hello", 3.14, [1, 2, 3]])
set2 = Set([1, 2, "world", 3.14])

intersection_set = intersect(set1, set2)
union_set = union(set1, set2)
isequal_set = issetequal(set1, set2)
sub_set = issubset(set1, set2)

println("Множество 1 : ", set1)
println("Множество 2 : ", set2)
println("Пересечение : ", intersection_set)
println("Объединение : ", union_set)
println("Эквивалентности множеств : ", isequal_set)
println("Подмножество : ", sub_set)

Множество 1 : Set(Any["hello", 3.14, [1, 2, 3], 1])
Множество 2 : Set(Any[2, 3.14, 1, "world"])
Пересечение : Set(Any[3.14, 1])
Объединение : Set(Any[2, "hello", 3.14, [1, 2, 3], 1, "world"])
Эквивалентности множеств : false
Подмножество : false


In [62]:
# Задания 3
# Задания 3.1 до 3.3
N = 25
array_3_1 = collect(1:N)
array_3_2 = reverse(collect(1:N))
array_3_3 = [1:N; N-1:-1:1]

println("Задания 3.1 : ", array_3_1)
println("Задания 3.2 : ", array_3_2)
println("Задания 3.3 : ", array_3_3)

Задания 3.1 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
Задания 3.2 : [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Задания 3.3 : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [63]:
# Задания 3.4 до 3.9
tmp = [4, 6, 3]

array_3_5 = fill(tmp[1], 10)
array_3_6 = repeat([tmp], 10)
array_3_7 = vcat(fill(tmp[1], 11), fill(tmp[2], 10), fill(tmp[3], 10))
array_3_8 = vcat(fill(tmp[1], 10), fill(tmp[2], 20), fill(tmp[3], 30))
array_3_9 = repeat(2 .^ tmp, inner = [1, 1, 4])
count_six = count(x -> x == '6', string(array_3_9))

println("Задания 3.5 : ", array_3_5)
println("Задания 3.6 : ", array_3_6)
println("Задания 3.7 : ", array_3_7)
println("Задания 3.8 : ", array_3_8)
println("Задания 3.9 : ", array_3_9)
println("Количество цифр 6 в результате 3.9 : ", count_six)

Задания 3.5 : [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
Задания 3.6 : [[4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3], [4, 6, 3]]
Задания 3.7 : [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
Задания 3.8 : [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
Задания 3.9 : [16; 64; 8;;; 16; 64; 8;;; 16; 64; 8;;; 16; 64; 8]
Количество цифр 6 в результате 3.9 : 8


In [64]:
# Задания 3.10
using Statistics;
x_values = 3:0.1:6
y_values = [exp(x) * cos(x) for x in x_values]
mean_y = mean(y_values)
println("Задания 3.10. Среднее значение y : ", mean_y)

Задания 3.10. Среднее значение y : 53.11374594642971


In [ ]:
# # Задания 3.11
x_vector = [0.1^i for i in 3:3:36]
y_vector = [0.2^j for j in 1:3:34]
result_3_11 = [(x, y) for x in x_vector, y in y_vector]
println("Задания 3.11 : ", result_3_11)

Задания 3.11 : [(0.0010000000000000002, 0.2) (0.0010000000000000002, 0.0016000000000000003) (0.0010000000000000002, 1.2800000000000006e-5) (0.0010000000000000002, 1.0240000000000006e-7) (0.0010000000000000002, 8.192000000000005e-10) (0.0010000000000000002, 6.5536000000000055e-12) (0.0010000000000000002, 5.2428800000000056e-14) (0.0010000000000000002, 4.194304000000005e-16) (0.0010000000000000002, 3.3554432000000044e-18) (0.0010000000000000002, 2.684354560000004e-20) (0.0010000000000000002, 2.147483648000004e-22) (0.0010000000000000002, 1.7179869184000035e-24); (1.0000000000000004e-6, 0.2) (1.0000000000000004e-6, 0.0016000000000000003) (1.0000000000000004e-6, 1.2800000000000006e-5) (1.0000000000000004e-6, 1.0240000000000006e-7) (1.0000000000000004e-6, 8.192000000000005e-10) (1.0000000000000004e-6, 6.5536000000000055e-12) (1.0000000000000004e-6, 5.2428800000000056e-14) (1.0000000000000004e-6, 4.194304000000005e-16) (1.0000000000000004e-6, 3.3554432000000044e-18) (1.0000000000000004e-6, 2

In [ ]:
# Задания 3.12
M = 25
result_3_12 = [2^i / i for i in 1:M]
println("Задания 3.12 : ", result_3_12)

Задания 3.12 : [2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


In [ ]:
# Задания 3.13
N = 30
result_3_13 = ["fn$i" for i in 1:N]
println("Задания 3.13 : ", result_3_13)

Задания 3.13 : ["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


In [ ]:
# Задания 3.14
# Создание векторов x и y целочисленного типа
n = 250
x = rand(0:999, n)
y = rand(0:999, n)

# Формирование векторов
vector1 = y[2:end] .- x[1:end-1]
vector2 = [x[i] + 2x[i+1] - x[i+2] for i in 1:n-2]
vector3 = [sin(y[i]) / cos(x[i+1]) for i in 1:n-1]
sum_expo = sum([exp(-x[i+1]) / (x[i] +10)] for i in 1:n-1)

1-element Vector{Float64}:
 1.4713467696164503e-5

In [ ]:
# Вывод
println("Задания 3.14.1 : ", vector1)

Задания 3.14.1 : [55, -123, -72, -83, 668, -58, 58, -446, -284, -925, 313, -65, 640, -62, 2, 514, -162, 419, 395, 890, 76, -529, -277, 586, -179, 370, 154, -621, 485, 45, 834, -82, 141, -490, -190, -370, -902, -487, 158, 822, -59, 377, -337, -30, -317, -80, -11, 32, 124, -240, -431, -558, -405, -301, 48, 21, 93, -1, 728, 395, -63, -129, -356, -691, -368, 328, 431, 57, 228, -148, 698, -151, -170, 10, -199, 296, -454, -657, 325, -83, -464, -403, 222, 321, 692, 80, -170, 181, 682, -47, -266, -22, -405, -130, -754, -271, -636, -98, 554, -95, 250, -799, 17, -291, -251, 7, 664, -150, 465, 83, -227, 486, 215, 62, 85, -332, 596, -105, -389, 419, 441, -763, 881, 54, -470, 180, -769, -7, -478, -397, 360, -17, -48, 489, 53, -23, 316, -60, 238, 512, 529, -522, 127, 46, -670, -410, 4, 153, 231, 51, 16, 30, -332, 265, -550, -800, 313, 323, -265, -279, -645, -597, -191, -632, -258, 325, -228, 179, 501, 148, -459, 556, 422, 39, 117, -156, -270, -78, 231, -652, 635, -768, -262, 338, 338, -601, 751, -17

In [ ]:
println("Задания 3.14.2 : ", vector2)

Задания 3.14.2 : [797, 559, 2126, 134, 1467, 677, 533, 868, 2205, 995, 1986, 1245, 636, 99, 477, 539, 608, 1311, 377, -562, 985, 1728, 264, 1836, 1200, 952, 1353, 707, 2256, 313, 1943, 458, 894, 1709, 873, 1614, 2050, 2573, 450, 735, 124, 165, 819, 2320, 1375, 492, 1469, 459, 795, 1566, 2033, 1946, 1534, 1973, 1790, -148, 1839, 965, -174, 471, 1420, 1678, 2177, 1269, 995, 415, 1, 570, 1598, 997, 580, 157, 726, 2237, -10, 1103, 2009, 1467, -309, 1281, 1540, 1446, 1385, -110, 625, 2124, 1078, -122, 483, 1727, 2053, 1582, -156, 1625, 799, 1159, 2051, 1106, 787, -336, 1167, 1584, 1676, 1319, 1727, 56, 944, 1335, -122, 1077, 573, 1279, 1231, 1500, 1830, 1150, 244, 1012, 73, -97, 2129, 411, 1006, 1277, 817, 1758, 1015, 1363, 2476, 238, 1839, 1451, -670, 1351, 1476, 744, 1916, 1259, 100, -146, 1719, 1027, 173, 1645, 2241, 966, 638, -136, 1070, 1220, 961, 1687, 597, 1086, 2807, 562, 317, 957, 1603, 1724, 1782, 467, 1293, 1476, 373, 1749, 1511, 841, 460, 2136, 1262, 300, 1476, 1422, 1542, 1653,

In [ ]:
println("Задания 3.14.3 : ", vector3)

Задания 3.14.3 : [-4.2808793402840335, 5.052782875536123, -24.33570707460792, 1.4823058801626103, -0.5644909464728004, -4.422173695396321, -0.683102130246784, 0.37899742612235077, -1.003975230287573, -0.7462479256211241, 1.412681973482235, 1.0265051250681847, -0.22868519211337449, 0.7513406222135456, -1.1842200852760154, -1.2587009945728846, 52.3130101719231, 1.5353269869137294, 1.3380421566214038, 1.0535207594687757, 0.4669966167554453, -0.2557246067049243, -0.5545181845530521, 2.8653067561499657, 1.0582733748736104, 1.18933985022893, 0.15582681371560447, -1.1215925811396859, 0.2892751044267637, 0.33540554674186807, 2.390796679509297, -0.6913063611935918, 3.3187864067852946, 0.7333265084887703, -2.5715551468126248, 2.264373022055517, 2.0457289116613135, 0.6865071819837713, -222.24343113422444, 1.0993931262200791, 0.46011923664239185, 0.23409224732110814, 0.035786869938577666, -0.05127218187227444, -1.0387472292383035, 0.7819933501169753, -0.9992744873818619, 0.9147156531528382, 0.4304

In [ ]:
println("Задания 3.14.4 : ", sum_expo)

Задания 3.14.4 : [1.4713467696164503e-5]


In [ ]:
# Задания 3.14.5
# выберите элементы вектора y, значения больше 600
indices_gt_600 = findall(y .> 600)
values_gt_600 = y[indices_gt_600]

println("Значение больше 600 : ", values_gt_600)
println("Индексы : ", indices_gt_600)

Значение больше 600 : [966, 726, 730, 741, 768, 842, 923, 849, 807, 859, 895, 887, 793, 779, 744, 996, 997, 993, 875, 981, 833, 677, 681, 701, 912, 910, 831, 714, 694, 754, 992, 651, 619, 730, 842, 742, 769, 765, 652, 836, 675, 768, 684, 866, 747, 606, 713, 852, 827, 993, 680, 868, 917, 841, 990, 780, 739, 947, 989, 836, 766, 843, 776, 609, 625, 801, 707, 706, 680, 926, 658, 900, 833, 905, 784, 622, 953, 955, 976, 634, 824, 753, 984, 887, 845, 792, 763, 782, 836, 709, 914, 674, 701, 953, 916, 767, 880, 763, 790, 841, 653, 739]
Индексы : [2, 5, 6, 7, 12, 13, 14, 17, 19, 20, 21, 25, 26, 27, 28, 30, 31, 32, 33, 40, 41, 45, 46, 49, 56, 59, 60, 63, 67, 70, 72, 75, 76, 80, 84, 85, 86, 87, 88, 90, 92, 93, 99, 100, 104, 107, 108, 110, 113, 114, 115, 116, 118, 122, 124, 125, 127, 133, 136, 138, 139, 142, 151, 153, 155, 159, 167, 168, 169, 170, 171, 173, 174, 175, 176, 177, 180, 182, 185, 186, 188, 191, 199, 201, 204, 205, 207, 210, 213, 214, 216, 220, 227, 228, 231, 232, 234, 238, 239, 240, 245

In [ ]:
# Задания 3.14.6
x_values_gt_600 = x[indices_gt_600]
println("Значения 𝑥, соответствующие значениям > 600 : ", x_values_gt_600)

Значения 𝑥, соответствующие значениям > 600 : [228, 62, 799, 193, 907, 283, 228, 296, 464, 5, 97, 972, 409, 590, 637, 952, 159, 957, 130, 11, 395, 998, 383, 258, 523, 103, 152, 847, 125, 683, 274, 818, 40, 96, 421, 77, 685, 822, 205, 635, 790, 468, 312, 300, 762, 49, 641, 80, 778, 618, 783, 684, 176, 919, 726, 555, 856, 248, 530, 826, 256, 853, 537, 734, 857, 665, 934, 501, 425, 510, 985, 411, 866, 667, 778, 681, 736, 940, 296, 875, 226, 645, 339, 255, 922, 156, 436, 19, 609, 929, 747, 684, 428, 93, 349, 160, 57, 451, 256, 771, 290, 315]


In [ ]:
# Задания 3.14.7
using Statistics
mean_x = mean(x)
sqrt_vec = abs.(x .- mean_x) .^ (1/2)
print("Задания 3.14.7 : ", sqrt_vec)

Задания 3.14.7 : [19.76238851960967, 17.10111107501498, 7.0393181487982215, 16.986818418997714, 21.411398833331745, 16.689877171507284, 18.09552430851342, 3.5281723313919886, 12.472048749102932, 21.71524809897414, 8.089993819527923, 19.660925715743907, 15.40934781228589, 17.10111107501498, 20.43154423923948, 13.617929358019154, 14.98158870080206, 11.508605475903671, 7.513188404399292, 22.70347990947643, 20.577852171691777, 15.509738875945011, 10.656078077792037, 14.813777371082637, 21.249752939740265, 10.556893482459694, 8.339784169869148, 10.795925157206307, 3.0737599125500967, 20.773829690261735, 19.01178581827599, 20.89382683952368, 19.759757083527113, 15.445128681885432, 15.282408187193536, 6.127968668327215, 21.830071003091128, 20.434089164922426, 17.394021961582087, 22.570954787070928, 11.200357137163081, 21.31778600136515, 10.837342847764852, 13.65840400632519, 21.8529631858016, 11.723821902434375, 11.46507740924587, 12.188191006051719, 16.2002469116986, 14.337084780386842, 19.8

In [ ]:
# Задания 3.14.8
count_below_200 = count(x -> x <= 200, values_gt_600)
println("Задания 3.14.8. Количество элементов <= 200 : ", count_below_200)

Задания 3.14.8. Количество элементов <= 200 : 0


In [ ]:
# Задания 3.14.9
even_count = count(iseven, x)
odd_count = count(isodd, x)
println("Задания 3.14.9 : Чётные : ", even_count)
println(" Нечётные : ", odd_count)

Задания 3.14.9 : Чётные : 124
 Нечётные : 126


In [ ]:
# 3.14.10
divisible_by_7_count = count(x -> x % 7 == 0, x)
println("Задания 3.14.10 : Количество элементов, кратных 7: ", divisible_by_7_count)

Задания 3.14.10 : Количество элементов, кратных 7: 28


In [ ]:
# 3.14.11
sorted_indices = sortperm(y)
sorted_x = x[sorted_indices]
println("Задания 3.14.11: Отсортированный x по возрастанию y : ", sorted_x)

Задания 3.14.11: Отсортированный x по возрастанию y : [241, 906, 912, 511, 366, 263, 565, 505, 22, 966, 72, 292, 676, 144, 707, 455, 429, 799, 638, 320, 559, 730, 513, 641, 938, 405, 580, 772, 911, 249, 570, 335, 991, 102, 655, 262, 815, 388, 543, 419, 109, 343, 175, 782, 669, 976, 103, 388, 336, 761, 854, 88, 997, 26, 9, 125, 911, 624, 620, 634, 247, 109, 275, 508, 526, 754, 366, 759, 22, 73, 382, 389, 988, 751, 851, 960, 50, 599, 301, 66, 908, 478, 245, 240, 373, 563, 174, 321, 301, 907, 886, 669, 726, 154, 725, 884, 992, 851, 360, 722, 487, 428, 157, 862, 375, 951, 400, 627, 341, 403, 307, 967, 823, 753, 768, 864, 578, 984, 990, 915, 159, 700, 859, 387, 79, 412, 809, 936, 329, 867, 520, 843, 964, 354, 344, 294, 120, 581, 579, 802, 201, 842, 558, 674, 764, 941, 84, 314, 49, 734, 40, 681, 857, 875, 818, 205, 290, 985, 684, 790, 998, 783, 425, 383, 312, 125, 258, 428, 501, 934, 929, 641, 847, 62, 799, 96, 856, 315, 193, 77, 637, 762, 645, 683, 436, 451, 822, 256, 160, 907, 468, 685, 53

In [ ]:
# 3.14.12
top_10_x = sorted_x[1:10]
println("Задания 3.14.12: Элементы вектора x в десятке наибольших : ", top_10_x)

Задания 3.14.12: Элементы вектора x в десятке наибольших : [241, 906, 912, 511, 366, 263, 565, 505, 22, 966]


In [ ]:
# 3.14.13
unique_x = unique(x)
println("Задания 3.14.13: Уникальные элементы x : ", unique_x)

Задания 3.14.13: Уникальные элементы x : [911, 228, 570, 809, 62, 799, 193, 508, 676, 992, 455, 907, 283, 103, 335, 296, 388, 464, 5, 97, 761, 634, 301, 972, 409, 590, 637, 511, 952, 159, 957, 130, 759, 754, 558, 997, 938, 823, 11, 395, 66, 403, 707, 998, 383, 389, 669, 258, 726, 915, 990, 862, 768, 864, 523, 120, 152, 581, 843, 847, 859, 366, 125, 201, 526, 683, 294, 274, 262, 641, 818, 40, 908, 753, 405, 96, 906, 627, 620, 421, 77, 685, 822, 205, 154, 635, 941, 790, 468, 144, 912, 343, 782, 312, 300, 886, 730, 762, 578, 599, 49, 387, 80, 341, 778, 618, 783, 684, 321, 176, 429, 22, 400, 919, 109, 555, 559, 856, 513, 867, 884, 964, 248, 9, 936, 530, 520, 826, 256, 79, 314, 853, 428, 984, 751, 245, 275, 157, 725, 537, 579, 734, 360, 857, 988, 26, 478, 665, 851, 764, 655, 292, 772, 543, 382, 934, 501, 425, 510, 985, 344, 411, 866, 667, 681, 487, 722, 736, 320, 940, 336, 638, 875, 73, 226, 72, 240, 645, 375, 966, 354, 373, 412, 563, 339, 174, 255, 329, 922, 156, 419, 436, 815, 991, 19, 62

In [ ]:
# Задания 4
squares = [i^2 for i in 1:100]
print("Массив squares: ", squares)

Массив squares: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

In [ ]:
# Задания 5
using Primes
myprimes = primes(1000)[1:168]

# Определите 89-е наименьшее простое число.
prime_89 = myprimes[89]
# Получите срез массива с 89-го до 99-го элемента включительно.
slice_89_to_99 = myprimes[89:99]

println("89-е простое число: ", prime_89)
println("Срез массива с 89-го до 99-го элемента myprimes: ", slice_89_to_99)

89-е простое число: 461
Срез массива с 89-го до 99-го элемента myprimes: [461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]


In [ ]:
# Задания 6
# 6.1
sum_6_1 = sum(i -> i^3 + 4i^2, 10:100)
print("6.1. Сумма выражения: ", sum_6_1)

6.1. Сумма выражения: 26852735

In [ ]:
# 6.2
M = 25
sum_6_2 = sum(i -> (2^i / i) + (3^i / i^2), 1:M)
print("6.2. Сумма выражения : ", sum_6_2)

6.2. Сумма выражения : 2.1291704368143802e9

In [ ]:
# 6.3
sum_6_3 = sum(prod(2 * i / (2 * i -1) for i in 1:n) for n in 1:20)
println("6.3. Сумма выражения : ", sum_6_3)

6.3. Сумма выражения : 111.00217926389996
